# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a7d4190565581f23b14ead61c72d1b461372daca1703c0696a81740724d9feb8b802c80f2b7fd2643c5bf1b87f9ad2e6b7f5e17274caa85ca021a3846c26198

test:
  secret_key_base: d5ba847d22dc5dea71e73c1458a574bebe5a845a2a6c298455261b9745f2001a486d2a65251050577bb0909cc7dc601909fe38b99896aad06b7c7c916bc3bca3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
